SET CURRENT SQLID = 'TAXOWNER';
CREATE TABLESPACE TAXACCTS
    IN TAXDB
    USING STOGROUP TAXSG
    PRIQTY 720 SECQTY 144
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CLOSE NO;
CREATE TABLE TAX_ACCOUNT (
    PARCEL_NO          CHAR(12)      NOT NULL,
    TAX_YEAR           SMALLINT      NOT NULL,
    OWNER_NAME         VARCHAR(80)   NOT NULL,
    MAIL_ADDRESS_1     VARCHAR(60)   NOT NULL,
    MAIL_ADDRESS_2     VARCHAR(60)   NOT NULL WITH DEFAULT,
    STATUS_CODE        CHAR(1)       NOT NULL WITH DEFAULT 'A',
    ASSESSED_VALUE     DECIMAL(13,2) NOT NULL WITH DEFAULT 0,
    ANNUAL_TAX         DECIMAL(11,2) NOT NULL WITH DEFAULT 0,
    PAID_TO_DATE       DECIMAL(11,2) NOT NULL WITH DEFAULT 0,
    CURRENT_BALANCE    DECIMAL(11,2) NOT NULL WITH DEFAULT 0,
    LAST_PAYMENT_DATE  DATE,
    ROW_VERSION        INTEGER       NOT NULL WITH DEFAULT 1,
    CREATED_TS         TIMESTAMP     NOT NULL WITH DEFAULT,
    UPDATED_TS         TIMESTAMP     NOT NULL WITH DEFAULT,
    PRIMARY KEY (PARCEL_NO, TAX_YEAR),
    CHECK (STATUS_CODE IN ('A', 'D', 'L', 'W')),
    CHECK (CURRENT_BALANCE >= -999999.99)
) IN TAXDB.TAXACCTS
  AUDIT CHANGES;
CREATE UNIQUE INDEX TAX_ACCOUNT_PK
    ON TAX_ACCOUNT (PARCEL_NO, TAX_YEAR)
    USING STOGROUP TAXSG
    PRIQTY 360 SECQTY 72
    CLUSTER CLOSE NO;
CREATE INDEX TAX_ACCOUNT_OWNER_IX
    ON TAX_ACCOUNT (OWNER_NAME)
    USING STOGROUP TAXSG
    PRIQTY 180 SECQTY 36;
CREATE TABLESPACE TAXPAYTS
    IN TAXDB
    USING STOGROUP TAXSG
    PRIQTY 1440 SECQTY 288
    BUFFERPOOL BP8K0
    LOCKSIZE ROW
    CLOSE NO;
CREATE TABLE TAX_PAYMENT (
    RECEIPT_NO         CHAR(16)      NOT NULL,
    PARCEL_NO          CHAR(12)      NOT NULL,
    TAX_YEAR           SMALLINT      NOT NULL,
    PAYMENT_DATE       DATE          NOT NULL,
    AMOUNT             DECIMAL(11,2) NOT NULL,
    TENDER_CODE        CHAR(1)       NOT NULL,
    SOURCE_SYSTEM      CHAR(4)       NOT NULL,
    OPERATOR_ID        CHAR(8)       NOT NULL WITH DEFAULT USER,
    REVERSAL_FLAG      CHAR(1)       NOT NULL WITH DEFAULT 'N',
    POSTED_TS          TIMESTAMP     NOT NULL WITH DEFAULT,
    PRIMARY KEY (RECEIPT_NO),
    FOREIGN KEY TAX_PAYMENT_ACCOUNT (PARCEL_NO, TAX_YEAR)
        REFERENCES TAX_ACCOUNT (PARCEL_NO, TAX_YEAR)
        ON DELETE RESTRICT,
    CHECK (AMOUNT > 0),
    CHECK (TENDER_CODE IN ('A', 'C', 'W')),
    CHECK (REVERSAL_FLAG IN ('Y', 'N'))
) IN TAXDB.TAXPAYTS
  AUDIT CHANGES;
CREATE UNIQUE INDEX TAX_PAYMENT_PK
    ON TAX_PAYMENT (RECEIPT_NO)
    USING STOGROUP TAXSG
    PRIQTY 720 SECQTY 144;
CREATE INDEX TAX_PAYMENT_PARCEL_IX
    ON TAX_PAYMENT (PARCEL_NO, TAX_YEAR, PAYMENT_DATE DESC)
    USING STOGROUP TAXSG
    PRIQTY 720 SECQTY 144
    CLUSTER;
CREATE TABLE TAX_PAYMENT_ERROR (
    ERROR_ID           BIGINT GENERATED ALWAYS AS IDENTITY,
    RECEIPT_NO         CHAR(16),
    PARCEL_NO          CHAR(12),
    REASON_CODE        CHAR(4)       NOT NULL,
    SQL_CODE           INTEGER,
    SOURCE_RECORD      VARCHAR(500)  FOR BIT DATA,
    CREATED_TS         TIMESTAMP     NOT NULL WITH DEFAULT,
    RESOLVED_FLAG      CHAR(1)       NOT NULL WITH DEFAULT 'N',
    RESOLVED_BY        CHAR(8),
    RESOLVED_TS        TIMESTAMP,
    PRIMARY KEY (ERROR_ID),
    CHECK (RESOLVED_FLAG IN ('Y', 'N'))
) IN TAXDB.TAXPAYTS
  AUDIT CHANGES;
CREATE VIEW ACTIVE_TAX_BALANCE
    (PARCEL_NO, TAX_YEAR, OWNER_NAME, ANNUAL_TAX,
     PAID_TO_DATE, CURRENT_BALANCE, LAST_PAYMENT_DATE) AS
SELECT PARCEL_NO, TAX_YEAR, OWNER_NAME, ANNUAL_TAX,
       PAID_TO_DATE, CURRENT_BALANCE, LAST_PAYMENT_DATE
  FROM TAX_ACCOUNT
 WHERE STATUS_CODE = 'A';
CREATE TRIGGER TAX_ACCOUNT_UPDATE_TS
    NO CASCADE BEFORE UPDATE ON TAX_ACCOUNT
    REFERENCING NEW AS N OLD AS O
    FOR EACH ROW MODE DB2SQL
    SET N.UPDATED_TS = CURRENT TIMESTAMP;
CREATE TRIGGER TAX_PAYMENT_IMMUTABLE
    NO CASCADE BEFORE DELETE ON TAX_PAYMENT
    REFERENCING OLD AS O
    FOR EACH ROW MODE DB2SQL
    SIGNAL SQLSTATE '75001'
       SET MESSAGE_TEXT = 'Tax payments must be reversed, not deleted';
GRANT SELECT ON TABLE ACTIVE_TAX_BALANCE TO PUBLIC;
GRANT SELECT, INSERT ON TABLE TAX_PAYMENT TO TXNPOSTP;
GRANT SELECT, UPDATE ON TABLE TAX_ACCOUNT TO TXNPOSTP;
GRANT INSERT ON TABLE TAX_PAYMENT_ERROR TO TXNPOSTP;
GRANT SELECT ON TABLE TAX_PAYMENT TO TXNINQP;
GRANT SELECT ON TABLE TAX_ACCOUNT TO TXNINQP;
COMMENT ON TABLE TAX_PAYMENT IS
    'Immutable receipt ledger populated by TXNPOST';
COMMIT;
RUNSTATS TABLESPACE TAXDB.TAXACCTS
    TABLE(ALL) INDEX(ALL) SHRLEVEL CHANGE;
RUNSTATS TABLESPACE TAXDB.TAXPAYTS
    TABLE(ALL) INDEX(ALL) SHRLEVEL CHANGE;
