import re

R = re.compile
ID = r"[A-Za-z_#@$][\w#@$\-]*"
VB_STR_COMMENT = [R(r"'"), R(r"(?i)(?<![\w.])REM\b")]
VB_UNITS = [("function", rf"^\s*(?:(?:Public|Private|Friend|Protected|Shared|Static|Overrides|Overridable)\s+)*(?:Sub|Function|Property\s+(?:Get|Let|Set))\s+(?P<name>{ID})"),
            ("class", rf"^\s*(?:(?:Public|Private|Friend|Partial|MustInherit|NotInheritable)\s+)*(?:Class|Module|Structure|Interface)\s+(?P<name>{ID})")]
VB_SECURITY_HINT = r"&\s*\w"

PACKS = [
    {"id": "vb6", "local_calls": "paren", "label": "Visual Basic 6", "family": "vb", "exts": ["frm", "ctl", "vbp", "dsr"], "names": ["visual basic 6", "vb6", "visual basic"],
     "detect": [r"^Attribute VB_Name", r"^VERSION 5\.00", r"^Begin VB\.Form", r"\bOn Error (GoTo|Resume)\b", r"\bDim\s+\w+\s+As\s+(New\s+)?\w+"],
     "quotes": '"', "line_comment": VB_STR_COMMENT, "units": VB_UNITS,
     "unit_end": {"function": R(r"^\s*End\s+(Sub|Function|Property)\b", re.I), "class": R(r"^\s*End\s+(Class|Module)\b", re.I)},
     "calls": [("calls", rf"^\s*Call\s+(?P<target>{ID})", "function"), ("uses", r"CreateObject\(\s*\"(?P<target>[\w.]+)\"", "external_system"),
               ("navigates_to", rf"\b(?P<target>frm\w+)\.Show\b", "screen"), ("calls", r"\bShell\s*\(?\s*\"(?P<target>[^\"]+)\"", "external_system")],
     "screens": [r"^Begin VB\.Form\s+(?P<target>\w+)"],
     "includes": [], "files": [("reads", r"\bOpen\s+\"(?P<target>[^\"]+)\"\s+For\s+(Input|Binary|Random)", "file"), ("writes", r"\bOpen\s+\"(?P<target>[^\"]+)\"\s+For\s+(Output|Append)", "file")],
     "fields": [rf"^\s*(?:Dim|Private|Public|Global)\s+(?P<name>{ID})\s+As\s+(?P<type>[\w.]+)"],
     "legacy": [("On Error GoTo / Resume Next error handling", r"\bOn Error (GoTo|Resume Next)\b"), ("GoTo / GoSub", r"^\s*(GoTo|GoSub)\s+\w+"),
                ("Variant / implicit typing", r"\bAs Variant\b|^\s*Dim\s+\w+\s*$"), ("DAO / RDO data access", r"\b(DAO\.|OpenDatabase|RDO|rdoConnection)"),
                ("ADO Recordset", r"ADODB\.(Recordset|Connection)"), ("OCX / ActiveX controls", r"^Object\s*=|\.ocx"), ("Win32 API Declare", r"^\s*(Private|Public)?\s*Declare\s+(Function|Sub)")],
     "frameworks": [("ADO", r"ADODB\."), ("Crystal Reports (embedded)", r"CRAXDRT|CrystalReport"), ("MS Access automation", r"Access\.Application|DoCmd\.")],
     "techs": [{"curated": "vb6"}],
     "blocks": [(r"^\s*(?:(?:Public|Private|Friend|Static)\s+)*(?:Sub|Function)\s+\w+", r"^\s*End\s+(Sub|Function)\b", "Sub/Function"),
                (r"^\s*If\b.*\bThen\s*$", r"^\s*End\s+If\b", "If/End If"), (r"^\s*With\b", r"^\s*End\s+With\b", "With/End With")]},
    {"id": "vba", "local_calls": "paren", "label": "VBA (Access / Excel)", "family": "vb", "exts": ["bas", "cls"], "names": ["vba", "access vba", "excel vba"],
     "detect": [r"\bDoCmd\.", r"\bCurrentDb\b", r"\bForms!", r"\bThisWorkbook\b", r"\bWorksheets?\(", r"^Attribute VB_Name"],
     "quotes": '"', "line_comment": VB_STR_COMMENT, "units": VB_UNITS,
     "unit_end": {"function": R(r"^\s*End\s+(Sub|Function|Property)\b", re.I)},
     "calls": [("calls", rf"^\s*Call\s+(?P<target>{ID})", "function"), ("navigates_to", r"DoCmd\.OpenForm\s+\"(?P<target>[^\"]+)\"", "screen"),
               ("calls", r"DoCmd\.OpenReport\s+\"(?P<target>[^\"]+)\"", "screen"), ("calls", r"DoCmd\.RunMacro\s+\"(?P<target>[^\"]+)\"", "function")],
     "files": [("reads", r"DoCmd\.TransferText\s+\w+,\s*\"?\w*\"?,\s*\"(?P<target>[^\"]+)\"", "table"),
               ("reads", r"CurrentDb\.OpenRecordset\(\s*\"(?P<target>\w+)\"", "table"),
               ("reads", r"OpenRecordset\(\s*\"(?P<target>\w+)\"", "table")],
     "sql_lines": r"\b(RunSQL|Execute|OpenRecordset)\b",
     "fields": [rf"^\s*(?:Dim|Private|Public)\s+(?P<name>{ID})\s+As\s+(?P<type>[\w.]+)"],
     "legacy": [("On Error GoTo / Resume Next error handling", r"\bOn Error (GoTo|Resume Next)\b"), ("DAO data access", r"\bDAO\.|CurrentDb"),
                ("SendKeys automation", r"\bSendKeys\b"), ("Linked tables / ODBC", r"\bODBC;|TransferDatabase")],
     "frameworks": [("MS Access", r"DoCmd\.|CurrentDb|Forms!"), ("Excel automation", r"ThisWorkbook|Worksheets?\(")],
     "techs": [{"curated": "ms-access", "when": r"DoCmd\.|CurrentDb|Forms!"}, {"curated": "vba"}],
     "blocks": [(r"^\s*(?:(?:Public|Private)\s+)*(?:Sub|Function)\s+\w+", r"^\s*End\s+(Sub|Function)\b", "Sub/Function"),
                (r"^\s*If\b.*\bThen\s*$", r"^\s*End\s+If\b", "If/End If")]},
    {"id": "vbnet", "label": "VB.NET", "family": "vb", "exts": ["vb"], "names": ["vb.net", "visual basic .net"],
     "detect": [r"^\s*Imports\s+System", r"^\s*End\s+(Module|Class|Namespace)\b", r"\bHandles\s+\w+\.\w+"],
     "quotes": '"', "line_comment": VB_STR_COMMENT, "units": VB_UNITS,
     "unit_end": {"function": R(r"^\s*End\s+(Sub|Function|Property)\b", re.I), "class": R(r"^\s*End\s+(Class|Module|Structure|Interface)\b", re.I)},
     "calls": [("uses", rf"\bNew\s+(?P<target>{ID})\s*\(", "class"), ("inherits", rf"^\s*Inherits\s+(?P<target>[\w.]+)", "class")],
     "includes": [(r"^\s*Imports\s+(?P<target>[\w.]+)", "module")],
     "fields": [rf"^\s*(?:Dim|Private|Public|Protected|Friend)\s+(?P<name>{ID})\s+As\s+(?:New\s+)?(?P<type>[\w.()]+)"],
     "legacy": [("On Error GoTo (VB6-style) error handling", r"\bOn Error (GoTo|Resume)"), ("Late binding (Option Strict Off)", r"Option\s+Strict\s+Off"),
                ("VB6 compatibility library", r"Microsoft\.VisualBasic\.Compatibility")],
     "frameworks": [("ASP.NET Web Forms", r"System\.Web\.UI|Inherits\s+System\.Web\.UI\.Page"), ("WinForms", r"System\.Windows\.Forms"),
                    ("ADO.NET", r"SqlConnection|OleDbConnection|OdbcConnection"), ("WCF", r"System\.ServiceModel")],
     "techs": [{"curated": "webforms", "when": r"System\.Web\.UI"}],
     "blocks": [(r"^\s*(?:(?:Public|Private|Protected|Friend|Shared|Overrides)\s+)*(?:Sub|Function)\s+\w+", r"^\s*End\s+(Sub|Function)\b", "Sub/Function"),
                (r"^\s*(?:(?:Public|Private|Partial)\s+)*Class\s+\w+", r"^\s*End\s+Class\b", "Class")]},
    {"id": "vbscript", "local_calls": "paren", "label": "VBScript / Classic ASP", "family": "vbscript", "exts": ["vbs", "asp", "inc", "wsf"], "names": ["vbscript", "classic asp", "asp"],
     "detect": [r"<%", r"Server\.CreateObject", r"Response\.Write", r"WScript\.", r"Request\.(Form|QueryString)"],
     "quotes": '"', "line_comment": VB_STR_COMMENT, "units": VB_UNITS[:1], "unit_end": {"function": R(r"^\s*End\s+(Sub|Function)\b", re.I)},
     "calls": [("uses", r"(?:Server\.|WScript\.)?CreateObject\(\s*\"(?P<target>[\w.]+)\"", "external_system"),
               ("navigates_to", r"Response\.Redirect\s*\(?\s*\"(?P<target>[\w./]+?)(?:\.asp)?[\"?]", "screen"),
               ("calls", rf"^\s*Call\s+(?P<target>{ID})", "function")],
     "includes": [(r"<!--\s*#include\s+(?:file|virtual)\s*=\s*\"(?P<target>[^\"]+)\"", "file")],
     "sql_lines": r"\.(Execute|Open)\b|\bSQL\s*=|\bstrSQL\b",
     "legacy": [("On Error Resume Next", r"\bOn Error Resume Next\b"), ("ADODB data access", r"ADODB\."),
                ("Session / Application state", r"\bSession\(|\bApplication\("), ("FileSystemObject", r"Scripting\.FileSystemObject")],
     "frameworks": [("Classic ASP", r"<%|Response\.|Request\."), ("Windows Script Host", r"WScript\.")],
     "techs": [{"curated": "vbscript"}, {"curated": "classic-asp", "when": r"<%|Response\.|Request\."}],
     "blocks": [(r"^\s*(?:Sub|Function)\s+\w+", r"^\s*End\s+(Sub|Function)\b", "Sub/Function")]},
    {"id": "rpg", "label": "RPG (IBM i)", "family": "ibmi", "exts": ["rpg", "rpgle", "sqlrpgle", "rpg38", "rpg36"], "names": ["rpg", "rpgle", "rpg iv", "ile rpg"],
     "detect": [r"^\*\*FREE", r"^.{5}[HFDC][ A-Z]", r"\bdcl-(s|ds|proc|f)\b", r"\b(BEGSR|ENDSR|EXSR|CHAIN|SETLL)\b"],
     "quotes": "'", "line_comment": [R(r"//")], "fixed_comment": lambda l: len(l) > 6 and l[6:7] == "*" or l.lstrip().startswith("//"),
     "upper_names": True,
     "units": [("paragraph", r"^.{5}C.{5}(?P<name>[A-Z0-9#@$]{1,14})\s+BEGSR\b"), ("paragraph", r"^\s*BEGSR\s+(?P<name>[A-Z0-9#@$_]+)"),
               ("function", r"\bdcl-proc\s+(?P<name>\w+)"), ("function", r"^.{5}P(?P<name>[A-Z0-9#@$_]{1,15})\s+B\b")],
     "unit_end": {"paragraph": R(r"\bENDSR\b", re.I), "function": R(r"\bend-proc\b|^.{5}P\s+.*\bE\b", re.I)},
     "calls": [("calls", r"\bEXSR\s+(?P<target>[A-Z0-9#@$_]+)", "paragraph"), ("calls", r"\bCALLP?\b\s*\(?\s*'?(?!QCMDEXC|QCMDCHK|QUS[A-Z]|QSYS|QDC|QWC|QMH)(?P<target>[A-Z0-9#@$_]+)'?", "program"),
               ("calls", r"\bCALLB\s+'(?P<target>\w+)'", "program")],
     "includes": [(r"/(?:COPY|INCLUDE)\s+(?P<target>[\w/,]+)", "copybook")],
     "files": [("uses", r"^.{5}F(?P<target>[A-Z0-9#@$_]{1,10})\s+[IUOC]", "database file"), ("uses", r"\bdcl-f\s+(?P<target>\w+)", "database file"),
               ("reads", r"\b(?:CHAIN|READE?|READP|SETLL|SETGT)\s*(?:\(\w\))?\s+(?P<target>[A-Z0-9#@$_]+)\s*;?\s*$", "database file"),
               ("writes", r"\b(?:WRITE|UPDATE|DELETE)\s*(?:\(\w\))?\s+(?P<target>[A-Z0-9#@$_]+)\s*;?\s*$", "database file")],
     "screens": [r"^.{5}F(?P<target>[A-Z0-9#@$_]{1,10}).*\bWORKSTN\b", r"\bdcl-f\s+(?P<target>\w+)\s+workstn\b", r"\bEXFMT\s+(?P<target>\w+)"],
     "sql_blocks": [r"EXEC\s+SQL\b(?P<sql>.*?)(?:END-EXEC|;)"],
     "fields": [r"\bdcl-s\s+(?P<name>\w+)\s+(?P<type>\w+(\(\d+(:\d+)?\))?)", r"^.{5}D(?P<name>[A-Z0-9#@$_]{1,15})\s+S\s+"],
     "legacy": [("fixed-form RPG (column-sensitive)", r"^.{5}[HFDICOP][ A-Z]"), ("numbered indicators (*INxx)", r"\*IN\d\d"), ("indicator operations (SETON/SETOF)", r"\bSET(ON|OF)\b(?!\s+LR\s*$)"),
                ("GOTO / TAG", r"\bGOTO\b|\bTAG\b"), ("RPG III opcodes (MOVE/Z-ADD/MULT)", r"\b(MOVEL?|Z-ADD|Z-SUB|MULT|DIV|IFEQ|DOWEQ)\b"),
                ("QCMDEXC command strings", r"\bQCMDEXC\b")],
     "dialects": [("RPG IV fully free (**FREE)", r"^\*\*FREE"), ("RPG IV free-form", r"\bdcl-s\b|/free"), ("RPG IV fixed-form", r"^.{5}D"), ("RPG III / RPG/400", r"^.{5}C")],
     "frameworks": [("Embedded SQL (SQLRPGLE)", r"EXEC\s+SQL"), ("5250 display files", r"WORKSTN|EXFMT")],
     "techs": [{"product": "ibm-i", "label": "IBM i (OS release not captured)"}],
     "blocks": [(r"\bBEGSR\b", r"\bENDSR\b", "BEGSR/ENDSR"), (r"\bdcl-proc\b", r"\bend-proc\b", "dcl-proc/end-proc")]},
    {"id": "cl", "label": "CL (IBM i control language)", "family": "ibmi", "exts": ["clp", "clle", "cl", "cmd"], "names": ["cl", "clle", "control language"],
     "detect": [r"^\s*PGM\b", r"\bDCL\s+VAR\(", r"\bCALL\s+PGM\(", r"\bENDPGM\b", r"\bOVRDBF\b"],
     "quotes": "'", "block_comment": ("/*", "*/"), "upper_names": True,
     "units": [("paragraph", r"^\s*(?P<name>[A-Z0-9#@$_]+):")],
     "calls": [("calls", r"\bCALL\s+PGM\((?:\w+/)?(?P<target>[A-Z0-9#@$_]+)\)", "program"),
               ("calls", r"\bSBMJOB\s+CMD\(CALL\s+PGM\((?:\w+/)?(?P<target>[A-Z0-9#@$_]+)\)", "program"),
               ("calls", r"\bGOTO\s+CMDLBL\((?P<target>\w+)\)", "paragraph")],
     "files": [("uses", r"\bOVRDBF\s+FILE\((?P<target>\w+)\)", "database file"), ("reads", r"\bRCVF\b.*?\bRCDFMT\((?P<target>\w+)\)", "database file"),
               ("uses", r"\bDCLF\s+FILE\((?:\w+/)?(?P<target>\w+)\)", "database file"), ("reads", r"\bCPYF\s+FROMFILE\((?:\w+/)?(?P<target>\w+)\)", "database file"),
               ("writes", r"\bCPYF\b.*\bTOFILE\((?:\w+/)?(?P<target>\w+)\)", "database file")],
     "legacy": [("MONMSG CPF0000 (swallow all errors)", r"MONMSG\s+MSGID\(CPF0000\)"), ("GOTO labels", r"\bGOTO\b")],
     "techs": [{"product": "ibm-i", "label": "IBM i (OS release not captured)"}], "blocks": [(r"^\s*PGM\b", r"\bENDPGM\b", "PGM/ENDPGM"), (r"\bDO\b", r"\bENDDO\b", "DO/ENDDO")]},
    {"id": "natural", "label": "Natural (Software AG)", "family": "natural", "exts": ["nsp", "nsn", "nss", "nsl", "nsm", "nsc", "nsg", "nsh", "nat"],
     "names": ["natural", "software ag natural"],
     "detect": [r"^\d{4}\s+DEFINE DATA", r"\bEND-DEFINE\b", r"\bCALLNAT\b", r"\bREAD\s+\w+\s+(BY|WITH)\b", r"\bINPUT USING MAP\b"],
     "quotes": "'\"", "line_comment": [R(r"^\d{4}\s*\*"), R(r"^\s*\*\s"), R(r"/\*")], "upper_names": True,
     "units": [("paragraph", r"\bDEFINE\s+SUBROUTINE\s+(?P<name>[\w#-]+)")], "unit_end": {"paragraph": R(r"\bEND-SUBROUTINE\b", re.I)},
     "calls": [("calls", r"\bCALLNAT\s+'(?P<target>[\w#-]+)'", "program"), ("calls", r"\bFETCH\s+(?:RETURN\s+)?'(?P<target>[\w#-]+)'", "program"),
               ("calls", r"\bPERFORM\s+(?P<target>[\w#-]+)", "paragraph"), ("calls", r"\bCALL\s+'(?P<target>[\w#-]+)'", "program")],
     "includes": [(r"\b(?:LOCAL|PARAMETER|GLOBAL)\s+USING\s+(?P<target>[\w#-]+)", "copybook"), (r"\bINCLUDE\s+(?P<target>[\w#-]+)", "copybook")],
     "files": [("reads", r"\b(?:READ|FIND|HISTOGRAM|GET)\s+(?:\(\d+\)\s+|FIRST\s+|NUMBER\s+|UNIQUE\s+)*(?P<target>[\w-]+)\s+(?:BY|WITH|PHYSICAL|LOGICAL|\*|$)", "Adabas file"),
               ("writes", r"\b(?:STORE|UPDATE|DELETE)\s+(?:RECORD\s+)?(?:IN\s+)?(?:FILE\s+)?(?P<target>[\w-]+)\b(?!\s*=)", "Adabas file"),
               ("uses", r"\bVIEW\s+OF\s+(?P<target>[\w-]+)", "Adabas file")],
     "screens": [r"\bINPUT\s+(?:\(\w+=\w+\)\s+)?USING\s+MAP\s+'(?P<target>[\w#-]+)'", r"\bWRITE\s+USING\s+(?:FORM|MAP)\s+'(?P<target>[\w#-]+)'"],
     "fields": [r"^\d{4}\s+\d\s+(?P<name>#?[\w-]+)\s*\((?P<type>[ANPIBLFDT][\d.,/]*)\)"],
     "legacy": [("Line-numbered source (reporting mode)", r"^\d{4}\s"), ("ESCAPE / REINPUT flow control", r"\b(ESCAPE (TOP|BOTTOM|ROUTINE)|REINPUT)\b"),
                ("Global data area (GDA)", r"\bGLOBAL USING\b"), ("Structured mode off / reporting mode", r"\bSET CONTROL\b|\bDO\b.*\bDOEND\b")],
     "frameworks": [("Adabas", r"\bVIEW OF\b|\bREAD\b|\bFIND\b"), ("Natural maps", r"\bUSING MAP\b")],
     "techs": [{"curated": "natural-adabas"}],
     "blocks": [(r"\bDEFINE DATA\b", r"\bEND-DEFINE\b", "DEFINE DATA/END-DEFINE"), (r"(?<!-)\bIF\b(?!.*\bEND-IF\b)", r"\bEND-IF\b", "IF/END-IF"),
                (r"\bDEFINE SUBROUTINE\b", r"\bEND-SUBROUTINE\b", "DEFINE SUBROUTINE/END-SUBROUTINE")]},
    {"id": "pli", "label": "PL/I", "family": "pli", "exts": ["pli", "pl1", "plinc", "pl"], "names": ["pl/i", "pli", "pl1"],
     "detect": [r"PROC(EDURE)?\s+OPTIONS\s*\(\s*MAIN", r"^\s*DCL\s+\w+", r"%INCLUDE", r"\bON\s+ENDFILE\b"],
     "quotes": "'", "block_comment": ("/*", "*/"), "upper_names": True,
     "units": [("function", r"^\s*(?P<name>[A-Z0-9_#@$]+)\s*:\s*PROC(?:EDURE)?\b")],
     "unit_end": {"function": R(r"^\s*END\s+[A-Z0-9_#@$]+\s*;", re.I)},
     "calls": [("calls", r"\bCALL\s+(?P<target>[A-Z0-9_#@$]+)", "function")],
     "includes": [(r"%INCLUDE\s+(?P<target>[\w()]+)", "copybook")],
     "files": [("reads", r"\bREAD\s+FILE\s*\(\s*(?P<target>\w+)\s*\)", "file"), ("writes", r"\b(?:WRITE|REWRITE)\s+FILE\s*\(\s*(?P<target>\w+)\s*\)", "file"),
               ("uses", r"\bDCL\s+(?P<target>\w+)\s+FILE\b", "file")],
     "sql_blocks": [r"EXEC\s+SQL\b(?P<sql>.*?);"],
     "fields": [r"^\s*DCL\s+(?:\d+\s+)?(?P<name>[A-Z0-9_#@$]+)\s+(?P<type>(FIXED|CHAR|BIN|DEC|PIC|FLOAT|BIT)[\w ()]*)"],
     "legacy": [("GOTO", r"\bGO\s*TO\b"), ("ON-units error handling", r"\bON\s+(ERROR|ENDFILE|CONVERSION|ZERODIVIDE)\b"), ("BASED/pointer storage", r"\bBASED\b")],
     "frameworks": [("CICS", r"EXEC\s+CICS"), ("DB2", r"EXEC\s+SQL"), ("IMS DL/I", r"PLITDLI")], "techs": [{"curated": "pli"}],
     "blocks": [(r"\bPROC(EDURE)?\b", r"^\s*END\s+\w+\s*;", "PROC/END"), (r"\b(?:DO|SELECT)\b(?!.*\bEND\s*;)", r"\bEND\s*;", "DO/SELECT/END")]},
    {"id": "asm", "label": "IBM Assembler (HLASM)", "family": "asm", "exts": ["asm", "mac", "mlc", "hlasm", "s"], "names": ["assembler", "hlasm", "bal"],
     "detect": [r"\bCSECT\b", r"\bBALR\b", r"^\S*\s+USING\s+\*", r"\bDS\s+\d*[CFHDXP]L?\d*", r"\bSTM\s+14,12"],
     "quotes": "'", "fixed_comment": lambda l: l.startswith("*") or l.startswith(".*"), "upper_names": True,
     "units": [("program", r"^(?P<name>[A-Z@#$][A-Z0-9@#$]{0,7})\s+(?:CSECT|RSECT|START)\b"), ("function", r"^(?P<name>[A-Z@#$][A-Z0-9@#$]{0,7})\s+ENTRY\b"),
               ("paragraph", r"^(?P<name>[A-Z@#$][A-Z0-9@#$]{0,7})\s+(?:DS\s+0H|EQU\s+\*)")],
     "calls": [("calls", r"^\S*\s+(?:CALL\s+|LINK\s+EP=|XCTL\s+EP=|LOAD\s+EP=)(?P<target>[A-Z@#$][A-Z0-9@#$]{0,7})", "program"),
               ("calls", r"=V\((?P<target>[A-Z@#$][A-Z0-9@#$]{0,7})\)", "program"), ("calls", r"\sBAL\s+\d+,(?P<target>[A-Z@#$][A-Z0-9@#$]{0,7})", "paragraph")],
     "includes": [(r"^\s+COPY\s+(?P<target>[A-Z@#$][A-Z0-9@#$]{0,7})", "copybook")],
     "files": [("uses", r"\bDCB\s+.*DDNAME=(?P<target>[A-Z@#$][A-Z0-9@#$]{0,7})", "dataset")],
     "legacy": [("24-bit addressing (AMODE 24)", r"AMODE\s+24|RMODE\s+24"), ("Self-modifying / EX instruction", r"\sEX\s+\d"),
                ("Hand-coded linkage (STM 14,12)", r"STM\s+14,12")],
     "frameworks": [("CICS", r"EXEC\s+CICS|DFHEIENT"), ("IMS DL/I", r"ASMTDLI|CBLTDLI")], "techs": [{"curated": "hlasm"}]},
    {"id": "rexx", "label": "REXX", "family": "script", "exts": ["rex", "rexx", "exec"], "names": ["rexx"],
     "detect": [r"^\s*/\*.*REXX.*\*/", r"\bADDRESS\s+(TSO|ISPEXEC|ISREDIT|MVS)\b", r"\bEXECIO\b", r"\bPARSE\s+(ARG|UPPER|VAR)\b"],
     "quotes": "'\"", "block_comment": ("/*", "*/"),
     "units": [("function", r"^(?P<name>[A-Za-z_][\w.]*)\s*:\s*(?:procedure\b|$)")],
     "calls": [("calls", r"\bCALL\s+(?P<target>[A-Za-z_][\w.]*)", "function"), ("calls", r"ADDRESS\s+TSO\s+['\"](?!ALLOC|FREE|SUBMIT|LISTD|DELETE|RENAME|SEND|PROFILE|EXECIO)(?:EXEC\s+)?'?(?P<target>[\w.()]+)", "program")],
     "files": [("reads", r"EXECIO\s+\S+\s+DISKR\s+(?P<target>\w+)", "dataset"), ("writes", r"EXECIO\s+\S+\s+DISKW\s+(?P<target>\w+)", "dataset"),
               ("uses", r"ALLOC(?:ATE)?\s+.*?DA(?:TASET)?\(['\"]?(?P<target>[\w.]+)", "dataset")],
     "screens": [r"ISPEXEC\s+['\"]?DISPLAY\s+PANEL\((?P<target>\w+)\)"],
     "legacy": [("SIGNAL (goto)", r"\bSIGNAL\s+(?!ON|OFF)\w+"), ("TSO/ISPF dependence", r"ADDRESS\s+(TSO|ISPEXEC)")],
     "frameworks": [("ISPF dialog", r"ISPEXEC"), ("TSO", r"ADDRESS\s+TSO")], "techs": [{"curated": "zos"}]},
    {"id": "clist", "label": "TSO CLIST", "family": "script", "exts": ["clist", "clst"], "names": ["clist"],
     "detect": [r"^\s*PROC\s+\d+", r"&SYSUID", r"\bCONTROL\s+(LIST|NOLIST|MSG)", r"^\s*ALLOC\s+F(ILE|I)\("],
     "quotes": "'", "block_comment": ("/*", "*/"),
     "calls": [("calls", r"\bEXEC\s+'?(?P<target>[\w.()]+)", "program"), ("calls", r"\bCALL\s+'?(?P<target>[\w.()]+)", "program")],
     "files": [("uses", r"ALLOC\s+.*?DA\(['\"]?(?P<target>[\w.&]+)", "dataset")], "screens": [r"ISPEXEC\s+DISPLAY\s+PANEL\((?P<target>\w+)\)"],
     "legacy": [("GOTO", r"\bGOTO\b")], "techs": [{"curated": "zos"}]},
    {"id": "easytrieve", "label": "Easytrieve", "family": "report", "exts": ["ezt", "eztrieve", "ezy"], "names": ["easytrieve", "easytrieve plus"],
     "detect": [r"^\s*FILE\s+\w+", r"^\s*JOB\s+INPUT\b", r"^\s*REPORT\b", r"^\s*PARM\s+", r"\bLINE\s+\d*\s*\w+"],
     "quotes": "'", "fixed_comment": lambda l: l.lstrip().startswith("*"), "upper_names": True,
     "units": [("paragraph", r"^(?P<name>[A-Z0-9#@$-]+)\.\s*PROC\b"), ("function", r"^\s*REPORT\s+(?P<name>[A-Z0-9#@$-]+)"),
               ("function", r"^\s*JOB\s+INPUT\s+(?P<name>[A-Z0-9#@$-]+)")],
     "unit_end": {"paragraph": R(r"\bEND-PROC\b", re.I)},
     "calls": [("calls", r"\bPERFORM\s+(?P<target>[A-Z0-9#@$-]+)", "paragraph"), ("calls", r"\bCALL\s+(?P<target>[A-Z0-9#@$]+)", "program")],
     "files": [("uses", r"^\s*FILE\s+(?P<target>[A-Z0-9#@$]+)", "dataset"), ("reads", r"\bJOB\s+INPUT\s+(?P<target>[A-Z0-9#@$]+)", "dataset"),
               ("writes", r"^\s*PUT\s+(?P<target>[A-Z0-9#@$]+)", "dataset")],
     "sql_lines": r"^\s*SQL\b|\bSELECT\b",
     "legacy": [("GOTO", r"\bGOTO\b"), ("Automatic report writer", r"^\s*REPORT\b")], "techs": [{"curated": "easytrieve"}],
     "blocks": [(r"(?<!-)\bPROC\b", r"\bEND-PROC\b", "PROC/END-PROC"), (r"^\s*IF\b", r"^\s*END-IF\b", "IF/END-IF")]},
    {"id": "sas", "label": "SAS", "family": "report", "exts": ["sas"], "names": ["sas"],
     "detect": [r"^\s*DATA\s+[\w.]+\s*(\(|;)", r"^\s*PROC\s+(SQL|SORT|MEANS|FREQ|PRINT|REPORT|EXPORT|IMPORT)\b", r"^\s*RUN\s*;", r"%MACRO\b", r"^\s*LIBNAME\b"],
     "quotes": "'\"", "block_comment": ("/*", "*/"), "line_comment": [R(r"^\s*\*[^;]*;")],
     "units": [("function", r"%MACRO\s+(?P<name>\w+)")], "unit_end": {"function": R(r"%MEND\b", re.I)},
     "calls": [("calls", r"%(?!MACRO|MEND|LET|IF|THEN|ELSE|DO|END|PUT|GLOBAL|LOCAL|INCLUDE|SYSFUNC|STR|NRSTR|EVAL|SCAN|UPCASE|SUBSTR|INDEX|LENGTH|QUOTE|UNQUOTE|BQUOTE|SUPERQ|SYSEVALF|SYMEXIST|RETURN|GOTO|ABORT)(?P<target>\w+)\s*[(;]", "function")],
     "includes": [(r"%INCLUDE\s+['\"](?P<target>[^'\"]+)['\"]", "file")],
     "files": [("writes", r"^\s*DATA\s+(?P<target>\w+\.\w+)", "SAS dataset"), ("reads", r"\b(?:SET|MERGE|UPDATE)\s+(?P<target>\w+\.\w+)", "SAS dataset"),
               ("reads", r"\bINFILE\s+['\"](?P<target>[^'\"]+)", "file"), ("writes", r"\bFILE\s+['\"](?P<target>[^'\"]+)", "file"),
               ("connects_to", r"^\s*LIBNAME\s+\w+\s+(?:ODBC|OLEDB)\b.*?\b(?:dsn|datasrc|noprompt)\s*=\s*[\"']?(?P<target>[\w.-]+)", "database"),
               ("connects_to", r"^\s*LIBNAME\s+\w+\s+(?:ORACLE|DB2|SQLSVR|TERADATA)\b.*?\b(?:path|database|server)\s*=\s*[\"']?(?P<target>[\w.-]+)", "database")],
     "sql_blocks": [r"PROC\s+SQL\b(?P<sql>.*?)\bQUIT\s*;"],
     "legacy": [("Hard-coded LIBNAME paths", r"LIBNAME\s+\w+\s+['\"][A-Z]:\\|LIBNAME\s+\w+\s+['\"]/"), ("DATA step MERGE without BY", r"\bMERGE\b(?![^;]*;\s*BY)")],
     "frameworks": [("PROC SQL", r"PROC\s+SQL"), ("SAS macro language", r"%MACRO"), ("SAS/ACCESS", r"LIBNAME\s+\w+\s+(ODBC|ORACLE|DB2|SQLSVR)")],
     "techs": [{"curated": "sas"}], "blocks": [(r"%MACRO\b", r"%MEND\b", "%MACRO/%MEND")]},
    {"id": "plsql", "label": "Oracle PL/SQL", "family": "sql", "exts": ["pks", "pkb", "pls", "prc", "fnc", "trg", "plsql"], "names": ["pl/sql", "plsql"],
     "merge_sql": True,
     "detect": [r"CREATE\s+(OR\s+REPLACE\s+)?(PACKAGE|PROCEDURE|FUNCTION|TRIGGER)\b", r"\bEXCEPTION\s+WHEN\b", r"\bDBMS_\w+\.", r"%(ROW)?TYPE\b"],
     "quotes": "'", "line_comment": [R(r"--")], "block_comment": ("/*", "*/"), "upper_names": True,
     "units": [("module", r"CREATE\s+(?:OR\s+REPLACE\s+)?PACKAGE\s+(?:BODY\s+)?(?P<name>[\w$#.\"]+)"),
               ("function", r"^\s*(?:CREATE\s+(?:OR\s+REPLACE\s+)?)?(?:PROCEDURE|FUNCTION)\s+(?P<name>[\w$#.\"]+)")],
     "calls": [("calls", r"\b(?P<target>[A-Z_][\w$#]*\.[A-Z_][\w$#]*)\s*\(", "function"), ("calls", r"\bEXEC(?:UTE)?\s+(?!IMMEDIATE\b)(?P<target>[A-Z_][\w$#.]*)", "function")],
     "legacy": [("Dynamic SQL (EXECUTE IMMEDIATE)", r"EXECUTE\s+IMMEDIATE"), ("UTL_FILE server file I/O", r"UTL_FILE\."),
                ("WHEN OTHERS THEN NULL (swallowed errors)", r"WHEN\s+OTHERS\s+THEN\s+NULL"), ("Database links", r"@\w+\b(?!\.)")],
     "frameworks": [("Oracle packages (DBMS_*)", r"\bDBMS_\w+"), ("UTL_HTTP / UTL_SMTP", r"UTL_(HTTP|SMTP|TCP)")],
     "techs": [{"product": "oracle-database"}],
     "blocks": [(r"\bBEGIN\b|\bCASE\b|\bCREATE\s+(?:OR\s+REPLACE\s+)?PACKAGE\s+BODY\b", r"\bEND\b(?!\s+(?:IF|LOOP|CASE)\b)", "BEGIN/END"),
                (r"\bLOOP\b(?<!END LOOP)", r"\bEND\s+LOOP\b", "LOOP/END LOOP"), (r"^\s*IF\b", r"\bEND\s+IF\b", "IF/END IF")]},
    {"id": "tsql", "label": "T-SQL (SQL Server)", "family": "sql", "exts": ["tsql"], "names": ["t-sql", "tsql", "transact-sql"], "merge_sql": True,
     "detect": [r"CREATE\s+(OR\s+ALTER\s+)?PROC(EDURE)?\b", r"@@(ROWCOUNT|ERROR|IDENTITY)", r"\bBEGIN\s+TRAN", r"\bsp_\w+", r"^\s*GO\s*$"],
     "quotes": "'", "line_comment": [R(r"--")], "block_comment": ("/*", "*/"), "upper_names": True,
     "units": [("function", r"CREATE\s+(?:OR\s+ALTER\s+)?(?:PROC(?:EDURE)?|FUNCTION|TRIGGER)\s+(?P<name>[\w\[\].]+)")],
     "calls": [("calls", r"\b(?:master\.\.)?(?P<target>xp_cmdshell)\b", "external_system"),
               ("calls", r"\bEXEC(?:UTE)?\s+(?!sp_executesql|master\.\.xp_|xp_)(?P<target>[\w\[\]]+(?:\.[\w\[\]]+)*)", "function")],
     "legacy": [("Dynamic SQL (EXEC / sp_executesql)", r"EXEC\s*\(|sp_executesql"), ("xp_cmdshell", r"xp_cmdshell"), ("Cursors", r"DECLARE\s+\w+\s+CURSOR"),
                ("Linked servers / OPENQUERY", r"OPENQUERY|OPENROWSET|\[\w+\]\.\[\w+\]\.\[\w+\]\.\["), ("@@ERROR error handling (pre-TRY/CATCH)", r"@@ERROR")],
     "techs": [{"product": "mssqlserver"}],
     "blocks": [(r"\bBEGIN\b(?!\s+(?:TRAN|TRANSACTION|DISTRIBUTED|DIALOG|CONVERSATION)\b)|\bCASE\b", r"\bEND\b(?!\s+(?:TRAN|CONVERSATION)\b)", "BEGIN/END")]},
    {"id": "powerbuilder", "local_calls": "paren", "label": "PowerBuilder (PowerScript)", "family": "4gl", "exts": ["srw", "sru", "srd", "srm", "srf", "srs", "sra", "srj"], "names": ["powerbuilder", "powerscript"],
     "detect": [r"\$PBExportHeader\$", r"^forward\s*$", r"\bglobal type \w+ from (window|userobject|datawindow)", r"\bdw_\w+\.(Retrieve|Update)\(", r"\bSQLCA\b"],
     "quotes": "\"'", "line_comment": [R(r"//")], "block_comment": ("/*", "*/"),
     "container": "class", "container_name": [r"global type (?P<name>\w+) from"],
     "units": [("function", r"^\s*event\s+(?:type\s+\w+\s+)?(?P<name>\w+)\s*[;(]"), ("function", r"^\s*(?:public|private|protected)?\s*(?:function|subroutine)\s+\w*\s*(?P<name>\w+)\s*\(")],
     "unit_end": {"function": R(r"^\s*end\s+(event|function|subroutine)\b", re.I)},
     "calls": [("navigates_to", r"\bOpen(?:WithParm|Sheet)?\s*\(\s*(?P<target>w_\w+)", "screen"), ("uses", r"\bdataobject\s*=\s*\"(?P<target>\w+)\"", "screen"),
               ("inherits", r"global type \w+ from (?P<target>\w+)", "class")],
     "sql_lines": r"^\s*(SELECT|INSERT|UPDATE|DELETE)\b",
     "screen_defs": [r"global type (?P<name>w_\w+) from window"],
     "legacy": [("Embedded SQL via SQLCA", r"USING\s+SQLCA|\bSQLCA\."), ("DataWindow", r"\bdw_\w+|datawindow"), ("PFC framework", r"\bpfc_|\bn_cst_")],
     "frameworks": [("DataWindow", r"datawindow|dw_\w+"), ("PFC", r"\bpfc_")], "techs": [{"curated": "powerbuilder"}]},
    {"id": "coldfusion", "unit_scope": "brace", "local_calls": "paren", "label": "ColdFusion (CFML)", "family": "webscript", "exts": ["cfm", "cfc", "cfml"], "names": ["coldfusion", "cfml"],
     "detect": [r"<cf(query|set|output|if|include|component|function|form)\b", r"\bcomponent\s+(extends|output|displayname)?"],
     "quotes": "\"'", "block_comment": ("<!---", "--->"),
     "units": [("function", r"<cffunction\s+name\s*=\s*\"(?P<name>\w+)\""), ("function", r"\bfunction\s+(?P<name>\w+)\s*\(")],
     "unit_end": {"function": R(r"</cffunction>|^\s*\}\s*$", re.I)},
     "calls": [("calls", r"<cfinvoke\s+component\s*=\s*\"(?P<target>[\w.]+)\"", "class"), ("uses", r"createObject\(\s*\"component\"\s*,\s*\"(?P<target>[\w.]+)\"", "class"),
               ("navigates_to", r"<cflocation\s+url\s*=\s*\"(?P<target>[\w/]+?)(?:\.cfm)?[\"?]", "screen")],
     "includes": [(r"<cfinclude\s+template\s*=\s*\"(?P<target>[^\"]+)\"", "file")],
     "files": [("connects_to", r"datasource\s*=\s*\"#?(?P<target>[\w.]+)#?\"", "database")],
     "sql_blocks": [r"<cfquery\b[^>]*>(?P<sql>.*?)</cfquery>"],
     "legacy": [("Unparameterised queries (#var# in cfquery)", r"<cfquery"), ("Application.cfm (pre-CF7 app model)", r"Application\.cfm")],
     "frameworks": [("ColdFusion", r"<cf\w+")], "techs": [{"product": "coldfusion"}]},
    {"id": "php", "unit_scope": "brace", "local_calls": "paren", "label": "PHP", "family": "webscript", "exts": ["php", "php3", "php4", "php5", "phtml"], "names": ["php"],
     "detect": [r"<\?php", r"\$_(GET|POST|REQUEST|SESSION)\[", r"\bmysql_query\s*\(", r"\becho\s+\$"],
     "quotes": "\"'", "line_comment": [R(r"//"), R(r"#(?!\[)")], "block_comment": ("/*", "*/"),
     "units": [("function", r"\bfunction\s+(?P<name>\w+)\s*\("), ("class", r"^\s*(?:abstract\s+|final\s+)?class\s+(?P<name>\w+)")],
     "calls": [("uses", r"\bnew\s+(?P<target>\w+)\s*\(", "class"), ("navigates_to", r"header\(\s*['\"]Location:\s*(?P<target>[\w/]+?)(?:\.php)?['\"?]", "screen")],
     "includes": [(r"\b(?:include|require)(?:_once)?\s*\(?\s*['\"](?P<target>[^'\"]+)['\"]", "file")],
     "files": [("connects_to", r"\b(?:mysql_connect|mysqli_connect|mssql_connect|pg_connect)\s*\(\s*['\"](?:host=)?(?P<target>[\w.-]+)", "database")],
     "legacy": [("mysql_* API (removed in PHP 7)", r"\bmysql_(query|connect|fetch_\w+|select_db)\s*\("), ("register_globals-era input", r"\$HTTP_(GET|POST)_VARS"),
                ("ereg / split (removed)", r"\b(ereg|eregi|split)\s*\("), ("Short open tags", r"<\?(?!php|=|xml)")],
     "frameworks": [("PDO", r"\bnew\s+PDO\b"), ("mysqli", r"\bmysqli_"), ("Legacy mysql_*", r"\bmysql_")],
     "techs": [{"product": "php", "version": "5.6", "unconfirmed": True, "when": r"\bmysql_(query|connect)\s*\("},
               {"product": "php", "when": r"^(?![\s\S]*\bmysql_(query|connect)\s*\()"}]},
    {"id": "perl", "unit_scope": "brace", "local_calls": "paren", "label": "Perl", "family": "script", "exts": ["pl", "pm", "cgi", "t"], "names": ["perl"],
     "detect": [r"^#!.*\bperl\b", r"^\s*use\s+strict\s*;", r"\bmy\s+[\$@%]\w+", r"\bDBI->connect\b"],
     "quotes": "\"'", "line_comment": [R(r"#")],
     "units": [("function", r"^\s*sub\s+(?P<name>\w+)"), ("module", r"^\s*package\s+(?P<name>[\w:]+)\s*;")],
     "calls": [("calls", r"\bsystem\s*\(\s*['\"](?P<target>[\w./-]+)", "external_system")],
     "includes": [(r"^\s*(?:use|require)\s+(?P<target>[A-Z][\w:]+)", "module")],
     "files": [("connects_to", r"DBI->connect\(\s*['\"]dbi:(?P<target>\w+:[^'\";]+)", "database"),
               ("reads", r"\bopen\s*\(?\s*\w+\s*,\s*['\"]<\s*(?P<target>[^'\"]+)['\"]", "file"),
               ("writes", r"\bopen\s*\(?\s*\w+\s*,\s*['\"]>>?\s*(?P<target>[^'\"]+)['\"]", "file")],
     "legacy": [("CGI.pm / cgi-bin", r"\buse\s+CGI\b|cgi-bin"), ("Two-argument open", r"\bopen\s*\(?\s*\w+\s*,\s*['\"][<>|]")],
     "frameworks": [("DBI", r"\bDBI\b"), ("CGI", r"\bCGI\b")], "techs": [{"product": "perl"}]},
    {"id": "shell", "unit_scope": "brace", "local_calls": "word", "label": "Unix shell (sh/ksh/bash)", "family": "script", "exts": ["sh", "ksh", "bash", "csh"], "names": ["shell", "bash", "ksh", "sh"],
     "detect": [r"^#!\s*/(usr/)?bin/(ba|k|c)?sh", r"^\s*\w+\(\)\s*\{", r"\$\{?\w+\}?", r"\bfi\s*$"],
     "quotes": "\"'", "line_comment": [R(r"(?<![\w$])#(?!!)")],
     "units": [("function", r"^\s*(?:function\s+)?(?P<name>[\w-]+)\s*\(\)\s*\{?"), ("function", r"^\s*function\s+(?P<name>[\w-]+)")],
     "calls": [("calls", r"(?:^|\s)(?:sh|ksh|bash|\.)\s+(?P<target>[\w./-]+\.(?:sh|ksh))", "program"),
               ("connects_to", r"\b(?P<target>sqlplus|db2|isql|bcp|sqlcmd|psql|mysql|sftp|ftp|scp|rsync|curl|wget|mailx?|sendmail|ssh)\b", "external_system")],
     "files": [("writes", r">>?\s*(?P<target>/[\w./-]+)", "file"), ("reads", r"<\s*(?P<target>/[\w./-]+)", "file")],
     "legacy": [("Plain FTP transfers", r"(?<![s\w])ftp\s"), ("Backtick command substitution", r"`[^`]+`"), ("Unquoted variables in tests", r"\[\s+\$\w+\s+(=|!=|-eq)")],
     "blocks": [(r"^\s*if\b", r"^\s*fi\b", "if/fi"), (r"\bcase\b.*\bin\s*$", r"^\s*esac\b", "case/esac")]},
    {"id": "batch", "label": "Windows batch", "family": "script", "exts": ["bat", "cmd"], "names": ["batch", "windows batch", "cmd"],
     "detect": [r"^@echo\s+off", r"(?i)^\s*goto\s+:?\w+", r"%~dp0", r"(?i)^\s*if\s+errorlevel\b"],
     "quotes": "\"", "line_comment": [R(r"(?i)^\s*(rem\b|::)")],
     "units": [("paragraph", r"^:(?P<name>\w+)")],
     "calls": [("calls", r"(?i)\bcall\s+:(?P<target>\w+)", "paragraph"), ("calls", r"(?i)\bcall\s+(?P<target>[\w.\\-]+\.(?:bat|cmd))", "program"),
               ("calls", r"(?i)\bgoto\s+:?(?P<target>\w+)", "paragraph"),
               ("connects_to", r"(?i)\b(?P<target>sqlcmd|osql|bcp|ftp|net\s+use|robocopy|xcopy|psexec)\b", "external_system")],
     "legacy": [("GOTO flow", r"(?i)\bgoto\b"), ("Plain FTP scripts (ftp -s)", r"(?i)\bftp\s+-s:"), ("net use with password", r"(?i)net\s+use\s+\S+\s+\S+\s+/user:")]},
    {"id": "powershell", "unit_scope": "brace", "local_calls": "word", "label": "PowerShell", "family": "script", "exts": ["ps1", "psm1", "psd1"], "names": ["powershell"],
     "detect": [r"^\s*param\s*\(", r"\b(Get|Set|New|Invoke|Import)-\w+", r"\$PSScriptRoot", r"\[CmdletBinding"],
     "quotes": "\"'", "line_comment": [R(r"#")], "block_comment": ("<#", "#>"),
     "units": [("function", r"^\s*function\s+(?P<name>[\w-]+)")],
     "calls": [("calls", r"\b(?P<target>[A-Z]\w+-[A-Z]\w+)\b", "function"), ("connects_to", r"-ServerInstance\s+['\"]?(?P<target>[\w.\\-]+)", "data_store")],
     "includes": [(r"\bImport-Module\s+['\"]?(?P<target>[\w.\\/-]+)", "module"), (r"^\s*\.\s+['\"]?(?P<target>[\w.\\/$-]+\.ps1)", "file")],
     "sql_lines": r"Invoke-Sqlcmd|-Query\b",
     "legacy": [("Invoke-Expression", r"\bInvoke-Expression\b|\biex\b"), ("Plain-text SecureString", r"ConvertTo-SecureString\s+.*-AsPlainText"),
                ("Windows PowerShell 2.0 syntax", r"#requires\s+-version\s+2")],
     "techs": [{"curated": "powershell51", "when": r"#requires\s+-version\s+[2-5]"}]},
    {"id": "python", "unit_scope": "indent", "local_calls": "paren", "label": "Python", "family": "script", "exts": ["py", "pyw"], "names": ["python", "python 2", "python 3"],
     "detect": [r"^\s*def\s+\w+\(", r"^\s*import\s+\w+", r"^\s*from\s+[\w.]+\s+import\b", r"^\s*print\s+['\"]"],
     "quotes": "\"'", "line_comment": [R(r"#")],
     "units": [("function", r"^\s*def\s+(?P<name>\w+)\s*\("), ("class", r"^\s*class\s+(?P<name>\w+)")],
     "calls": [("calls", r"subprocess\.\w+\(\s*\[?\s*['\"](?P<target>[\w./-]+)", "external_system")],
     "includes": [(r"^\s*import\s+(?P<target>[\w.]+)", "module"), (r"^\s*from\s+(?P<target>[\w.]+)\s+import", "module")],
     "legacy": [("Python 2 print statement", r"^\s*print\s+[^(=\s]"), ("Python 2 except syntax", r"except\s+\w+\s*,\s*\w+\s*:"),
                ("xrange / raw_input / unicode()", r"\b(xrange|raw_input|unicode|basestring)\s*\("), ("Python 2 string module functions", r"\bstring\.(join|split|replace)\(")],
     "techs": [{"product": "python", "version": "2.7", "when": r"^\s*print\s+[^(=\s]|except\s+\w+\s*,\s*\w+\s*:|\bxrange\s*\(|\braw_input\s*\("}]},
    {"id": "javascript", "unit_scope": "brace", "local_calls": "paren", "label": "JavaScript", "family": "js", "exts": ["js", "jsx", "mjs"], "names": ["javascript", "js"],
     "detect": [r"\bfunction\s+\w+\s*\(", r"\$\(\s*document\s*\)", r"\bvar\s+\w+\s*=", r"XMLHttpRequest|\$\.ajax"],
     "quotes": "\"'`", "line_comment": [R(r"//")], "block_comment": ("/*", "*/"),
     "units": [("function", r"\bfunction\s+(?P<name>\w+)\s*\("), ("function", r"\b(?:var|let|const)\s+(?P<name>\w+)\s*=\s*function\b"), ("class", r"^\s*class\s+(?P<name>\w+)")],
     "calls": [("calls", r"(?:\$\.(?:ajax|get|post|getJSON)|fetch)\s*\(\s*(?:\{\s*url\s*:\s*)?['\"](?P<target>/[\w./{}-]+)", "api_endpoint"),
               ("calls", r"url\s*:\s*['\"](?P<target>/[\w./{}-]+)", "api_endpoint"), ("calls", r"\.open\(\s*['\"](?:GET|POST)['\"]\s*,\s*['\"](?P<target>/[\w./-]+)", "api_endpoint")],
     "legacy": [("document.write", r"document\.write\s*\("), ("Synchronous XHR", r"\.open\([^)]*,\s*false\s*\)"), ("eval()", r"\beval\s*\("), ("ActiveXObject (IE only)", r"ActiveXObject")],
     "frameworks": [("jQuery", r"\$\(|jQuery"), ("AngularJS", r"angular\.module"), ("Knockout", r"\bko\.observable"), ("ExtJS", r"\bExt\.(define|create)")],
     "techs": [{"curated": "angularjs1", "when": r"angular\.module"}]},
    {"id": "delphi", "label": "Delphi / Object Pascal", "family": "4gl", "exts": ["pas", "dpr", "dpk", "inc"], "names": ["delphi", "pascal", "object pascal"],
     "detect": [r"^\s*unit\s+\w+\s*;", r"^\s*uses\b", r"^\s*(procedure|function)\s+T\w+\.", r"\bbegin\b[\s\S]*\bend\s*[;.]", r"^\s*program\s+\w+\s*;"],
     "quotes": "'", "line_comment": [R(r"//")], "block_comment": ("{", "}"),
     "container": "module", "container_name": [r"^\s*(?:unit|program|library)\s+(?P<name>[\w.]+)\s*;"],
     "units": [("class", r"^\s*(?P<name>T\w+)\s*=\s*class\b"), ("function", r"^\s*(?:procedure|function|constructor|destructor)\s+(?P<name>[\w.]+)")],
     "calls": [("uses", r"\b(?P<target>T[A-Z]\w+)\.Create\b", "class"), ("navigates_to", r"\b(?P<target>(?:frm|form|dlg)[A-Z]\w*|\w+Form\w*)\.Show(?:Modal)?\b", "screen")],
     "includes": [(r"^\s*uses\s+(?P<target>[\w.]+)", "module"), (r"\{\$I(?:NCLUDE)?\s+(?P<target>[\w.]+)\}", "file")],
     "sql_lines": r"SQL\.(Add|Text)|\.SQL\s*:=|CommandText",
     "legacy": [("BDE (Borland Database Engine)", r"\bTTable\b|\bTDatabase\b|DBTables|BDE"), ("with statements", r"^\s*with\s+\w+\s+do\b"), ("GOTO", r"\bgoto\b")],
     "frameworks": [("VCL", r"\bForms\b|\bTForm\b"), ("BDE", r"DBTables|TTable"), ("ADO (dbGo)", r"ADODB|TADOQuery")],
     "techs": [{"curated": "delphi-bde", "when": r"DBTables|\bTTable\b|BDE"}], "blocks": [(r"\bbegin\b|\bcase\b.*\bof\b|\btry\b|=\s*(?:packed\s+)?(?:class|record|object|interface)\b(?!\s*(?:;|of\b|\())|=\s*class\s*\([\w, ]+\)\s*$", r"\bend\b(?!\.)", "begin/end")]},
    {"id": "foxpro", "label": "Visual FoxPro", "family": "4gl", "exts": ["prg", "spr", "mpr", "qpr"], "names": ["foxpro", "visual foxpro", "vfp"],
     "detect": [r"^\s*(PROCEDURE|FUNCTION)\s+\w+", r"^\s*USE\s+\w+", r"^\s*SCAN\b", r"\bENDSCAN\b", r"\bDO\s+FORM\b", r"\bSQLEXEC\s*\("],
     "quotes": "\"'", "line_comment": [R(r"^\s*\*"), R(r"&&"), R(r"(?i)^\s*NOTE\b")], "upper_names": True,
     "units": [("function", r"^\s*(?:PROCEDURE|FUNCTION)\s+(?P<name>\w+)")], "unit_end": {"function": R(r"^\s*(ENDPROC|ENDFUNC|RETURN)\b", re.I)},
     "calls": [("calls", r"^\s*DO\s+(?!FORM|WHILE|CASE)(?P<target>\w+)", "function"), ("navigates_to", r"\bDO\s+FORM\s+(?P<target>\w+)", "screen")],
     "includes": [(r"SET\s+PROCEDURE\s+TO\s+(?P<target>\w+)", "file"), (r"#INCLUDE\s+['\"]?(?P<target>[\w.]+)", "file")],
     "files": [("connects_to", r"\bSQL(?:STRING)?CONNECT\s*\(\s*[\"'](?:DSN=)?(?P<target>[\w.-]+)", "database"),
               ("reads", r"^\s*USE\s+(?P<target>\w+)", "DBF table"), ("writes", r"\b(?:REPLACE|APPEND\s+BLANK|INSERT\s+INTO)\b.*?\bIN\s+(?P<target>\w+)", "DBF table")],
     "sql_lines": r"SQLEXEC\s*\(|^\s*SELECT\b",
     "legacy": [("Macro substitution (&var)", r"&\w+"), ("SCAN/ENDSCAN record loops", r"\bSCAN\b"), ("DBF tables", r"^\s*USE\s+\w+")],
     "techs": [{"curated": "visual-foxpro"}], "blocks": [(r"^\s*SCAN\b", r"\bENDSCAN\b", "SCAN/ENDSCAN"), (r"^\s*IF\b", r"^\s*ENDIF\b", "IF/ENDIF"), (r"^\s*DO\s+CASE\b", r"^\s*ENDCASE\b", "DO CASE/ENDCASE")]},
    {"id": "informix4gl", "label": "Informix 4GL", "family": "4gl", "exts": ["4gl", "4gs"], "names": ["informix 4gl", "4gl"],
     "detect": [r"^\s*MAIN\s*$", r"\bEND\s+MAIN\b", r"^\s*DATABASE\s+\w+", r"^\s*(FUNCTION|REPORT)\s+\w+\s*\(", r"\bOPEN\s+WINDOW\b"],
     "quotes": "\"'", "line_comment": [R(r"#"), R(r"--")], "block_comment": ("{", "}"), "upper_names": True,
     "units": [("function", r"^\s*(?:FUNCTION|REPORT)\s+(?P<name>\w+)\s*\("), ("function", r"^\s*(?P<name>MAIN)\s*$")],
     "unit_end": {"function": R(r"^\s*END\s+(FUNCTION|REPORT|MAIN)\b", re.I)},
     "calls": [("calls", r"\bCALL\s+(?P<target>\w+)\s*\(", "function"), ("calls", r"\bSTART\s+REPORT\s+(?P<target>\w+)", "function"),
               ("calls", r"\bRUN\s+['\"](?P<target>[\w./-]+)", "program")],
     "files": [("connects_to", r"^\s*DATABASE\s+(?P<target>\w+)", "database")],
     "screens": [r"\bOPEN\s+(?:WINDOW\s+\w+\s+AT\s+[\d,\s]+WITH\s+)?FORM\s+['\"]?(?P<target>\w+)", r"\bOPEN\s+FORM\s+\w+\s+FROM\s+['\"](?P<target>[\w/]+)"],
     "sql_lines": r"\b(SELECT|INSERT|UPDATE|DELETE)\b",
     "legacy": [("WHENEVER ERROR CONTINUE", r"WHENEVER\s+ERROR\s+CONTINUE"), ("Character-mode forms", r"\bOPEN\s+(WINDOW|FORM)\b")],
     "techs": [{"curated": "informix-4gl"}], "blocks": [(r"^\s*(FUNCTION|REPORT)\b|^\s*MAIN\s*$", r"^\s*END\s+(FUNCTION|REPORT|MAIN)\b", "FUNCTION/END FUNCTION")]},
    {"id": "progress", "label": "Progress 4GL / OpenEdge ABL", "family": "4gl", "exts": ["p", "w", "i", "cls"], "names": ["progress", "openedge", "abl", "progress 4gl"],
     "detect": [r"\bFOR\s+EACH\s+\w+", r"\bDEFINE\s+(VARIABLE|TEMP-TABLE|BUFFER|FRAME)\b", r"^\s*RUN\s+[\w./]+\.[pw]\b", r"\bFIND\s+(FIRST|LAST|NEXT)\s+\w+", r"\bEND\.\s*$"],
     "quotes": "\"'", "block_comment": ("/*", "*/"),
     "units": [("function", r"^\s*PROCEDURE\s+(?P<name>[\w-]+)\s*:"), ("function", r"^\s*FUNCTION\s+(?P<name>[\w-]+)\s+RETURNS\b")],
     "unit_end": {"function": R(r"^\s*END\s+(PROCEDURE|FUNCTION)\b", re.I)},
     "calls": [("calls", r"^\s*RUN\s+(?P<target>[\w./-]+?)(?:\.[pw])?[\s.(]", "program"), ("calls", r"^\s*RUN\s+(?P<target>[\w-]+)\s+IN\b", "function")],
     "includes": [(r"\{\s*(?P<target>[\w./-]+\.i)\b", "copybook")],
     "files": [("reads", r"\b(?:FOR\s+EACH|FIND\s+(?:FIRST|LAST|NEXT|PREV)?|CAN-FIND\s*\()\s*(?P<target>[\w-]+)\b", "OpenEdge table"),
               ("writes", r"^\s*(?:CREATE|DELETE)\s+(?P<target>[\w-]+)\s*\.", "OpenEdge table")],
     "screens": [r"\bDEFINE\s+FRAME\s+(?P<target>[\w-]+)"],
     "legacy": [("Shared variables", r"\bNEW\s+(GLOBAL\s+)?SHARED\b|\bSHARED\s+VARIABLE\b"), ("Character UI frames", r"\bDEFINE\s+FRAME\b")],
     "techs": [{"curated": "progress"}]},
]

EXT_INDEX = {}
for _p in PACKS:
    for _e in _p["exts"]:
        EXT_INDEX.setdefault(_e, []).append(_p)
BY_ID = {p["id"]: p for p in PACKS}
